# Generated by Django 5.2.10 on 2026-01-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_blog_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
